export const cityCopy = {
  ru: {
    greeting: 'С возвращением', overview: 'Ваше развитие — в одном месте', balance: 'Монеты', inProgress: 'Активное обучение', nextStep: 'Ваш следующий шаг', districts: 'Районы развития', cityNote: 'Учитесь, развивайте навыки и наблюдайте, как растёт ваш город.', noActive: 'Сейчас нет активного обучения', learningNote: 'Ваши курсы и история обучения.', skillsNote: 'Что уже получается и что нужно для следующего уровня.', recommendationsNote: 'Подобрано с учётом ваших навыков, цели и опыта.', achievementsNote: 'Ваши завершённые занятия и результаты обучения.', homeNote: 'Продолжайте обучение и двигайтесь к своей цели.', noDistrict: 'Пока нет подходящих рекомендаций для этого района.', openSkills: 'Посмотреть навыки', filters: 'Все рекомендации', reward: 'Награда', partner: 'При поддержке', more: 'Меню', close: 'Закрыть', clear: 'Очистить поиск',
    navigation: 'Навигация', home: 'Главная', learning: 'Моё обучение', city: 'Мой город', recommendations: 'Рекомендации', skills: 'Мои навыки', achievements: 'Достижения',
    quote: 'Развивайся сегодня — строй лучшее завтра', theme: 'Переключить тему', search: 'Поиск в рекомендациях…',
    eyebrow: 'ВАШ ГОРОД ВОЗМОЖНОСТЕЙ', headline: 'Знания сегодня —', subline: 'больше возможностей завтра', continue: 'Продолжить обучение', how: 'Мой карьерный путь',
    buildings: 'навыков в городе', completed: 'занятий завершено', available: 'рекомендаций', progress: 'Ваш прогресс', target: 'Следующая цель', current: 'Следующий шаг', all: 'Смотреть все', ai: 'Рекомендации от AI', recent: 'Последние достижения', empty: 'Первые достижения ещё впереди',
    banner: 'Карьерный рост — это путь, который ты строишь сам.', support: 'А мы рядом, чтобы поддержать.', explore: 'К моим рекомендациям', noResults: 'По вашему запросу ничего не найдено', level: 'УРОВЕНЬ', details: 'Подробнее',
  },
  kk: {
    greeting: 'Қайта оралуыңызбен', overview: 'Дамуыңыз — бір жерде', balance: 'Монеталар', inProgress: 'Оқу үстінде', nextStep: 'Келесі қадамыңыз', districts: 'Даму аудандары', cityNote: 'Оқып, дағдыларыңызды дамытыңыз — қалаңыз да өседі.', noActive: 'Қазір белсенді оқу жоқ', learningNote: 'Курстарыңыз және оқу тарихы.', skillsNote: 'Келесі деңгейге қажет дағдылар.', recommendationsNote: 'Дағдыларыңыз, мақсатыңыз және тәжірибеңізге сай.', achievementsNote: 'Аяқталған сабақтарыңыз және оқу нәтижелері.', homeNote: 'Оқуды жалғастырып, мақсатыңызға жақындаңыз.', noDistrict: 'Бұл ауданға сәйкес ұсыныстар әзірге жоқ.', openSkills: 'Дағдыларды көру', filters: 'Барлық ұсыныстар', reward: 'Марапат', partner: 'Қолдауымен', more: 'Мәзір', close: 'Жабу', clear: 'Іздеуді тазарту',
    navigation: 'Навигация', home: 'Басты бет', learning: 'Менің оқуым', city: 'Менің қалам', recommendations: 'Ұсыныстар', skills: 'Дағдыларым', achievements: 'Жетістіктер',
    quote: 'Бүгін дамы — ертеңгі күніңді жақсарт', theme: 'Тақырыпты ауыстыру', search: 'Ұсыныстардан іздеу…',
    eyebrow: 'СЕНІҢ МҮМКІНДІКТЕР ҚАЛАҢ', headline: 'Бүгінгі білім —', subline: 'ертеңгі мол мүмкіндік', continue: 'Оқуды жалғастыру', how: 'Менің мансап жолым',
    buildings: 'қаладағы дағдылар', completed: 'сабақ аяқталды', available: 'ұсыныс', progress: 'Сіздің прогресіңіз', target: 'Келесі мақсат', current: 'Келесі қадам', all: 'Барлығын көру', ai: 'AI ұсыныстары', recent: 'Соңғы жетістіктер', empty: 'Алғашқы жетістіктер әлі алда',
    banner: 'Мансаптық өсу — өзің салатын жол.', support: 'Ал біз қолдау көрсету үшін жаныңдамыз.', explore: 'Ұсыныстарыма өту', noResults: 'Сұрауыңыз бойынша ештеңе табылмады', level: 'ДЕҢГЕЙ', details: 'Толығырақ',
  },
  en: {
    greeting: 'Welcome back', overview: 'Your growth, all in one place', balance: 'Coins', inProgress: 'Active learning', nextStep: 'Your next step', districts: 'Growth districts', cityNote: 'Keep learning, develop your skills and watch your city grow.', noActive: 'No learning in progress yet', learningNote: 'Your courses and learning history.', skillsNote: 'Your strengths and the skills you need for your next level.', recommendationsNote: 'Selected for your skills, goals and experience.', achievementsNote: 'Your completed activities and learning results.', homeNote: 'Keep learning and move closer to your goal.', noDistrict: 'No recommendations for this district yet.', openSkills: 'Explore skills', filters: 'All recommendations', reward: 'Reward', partner: 'Supported by', more: 'Menu', close: 'Close', clear: 'Clear search',
    navigation: 'Navigation', home: 'Home', learning: 'My learning', city: 'My city', recommendations: 'Recommendations', skills: 'My skills', achievements: 'Achievements',
    quote: 'Grow today — build a better tomorrow', theme: 'Toggle theme', search: 'Search recommendations…',
    eyebrow: 'YOUR CITY OF OPPORTUNITIES', headline: 'Knowledge today.', subline: 'More possibilities tomorrow.', continue: 'Continue learning', how: 'My career path',
    buildings: 'skills in your city', completed: 'activities completed', available: 'recommendations', progress: 'Your progress', target: 'Next goal', current: 'Your next step', all: 'View all', ai: 'AI recommendations', recent: 'Latest achievements', empty: 'Your first achievements are ahead',
    banner: 'Career growth is a path you build yourself.', support: 'And we are here to support you.', explore: 'Explore recommendations', noResults: 'No results for your search', level: 'LEVEL', details: 'View details',
  },
}
